create extension if not exists "pgcrypto";
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null, created_at timestamptz not null default now());
create table public.episodes (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id) on delete cascade, title text not null, status text not null default 'draft' check (status in ('draft','scheduled','live','processing','published')), scheduled_at timestamptz, started_at timestamptz, ended_at timestamptz, created_at timestamptz not null default now());
create table public.prep_items (id uuid primary key default gen_random_uuid(), episode_id uuid not null references public.episodes(id) on delete cascade, author_id uuid not null references public.profiles(id) on delete cascade, kind text not null check (kind in ('topic','note','ai_prompt','question')), content text not null, created_at timestamptz not null default now());
create table public.guest_invites (id uuid primary key default gen_random_uuid(), episode_id uuid not null references public.episodes(id) on delete cascade, display_name text not null, token_hash text not null unique, expires_at timestamptz not null, created_at timestamptz not null default now());
create table public.media_assets (id uuid primary key default gen_random_uuid(), episode_id uuid references public.episodes(id) on delete cascade, owner_id uuid not null references public.profiles(id) on delete cascade, kind text not null check (kind in ('upload','raw_recording','edited_episode','intro_audio','thumbnail')), storage_path text not null, created_at timestamptz not null default now());
create table public.analytics_snapshots (id uuid primary key default gen_random_uuid(), episode_id uuid not null references public.episodes(id) on delete cascade, provider text not null, captured_at timestamptz not null default now(), metrics jsonb not null default '{}'::jsonb);
alter table public.profiles enable row level security;
alter table public.episodes enable row level security;
alter table public.prep_items enable row level security;
alter table public.guest_invites enable row level security;
alter table public.media_assets enable row level security;
alter table public.analytics_snapshots enable row level security;
create policy "profile self access" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "episode owner access" on public.episodes for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
create policy "prep via owned episode" on public.prep_items for all using (exists(select 1 from public.episodes e where e.id=episode_id and e.owner_id=auth.uid())) with check (exists(select 1 from public.episodes e where e.id=episode_id and e.owner_id=auth.uid()));
create policy "guest invite via owned episode" on public.guest_invites for all using (exists(select 1 from public.episodes e where e.id=episode_id and e.owner_id=auth.uid())) with check (exists(select 1 from public.episodes e where e.id=episode_id and e.owner_id=auth.uid()));
create policy "media owner access" on public.media_assets for all using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
create policy "analytics via owned episode" on public.analytics_snapshots for all using (exists(select 1 from public.episodes e where e.id=episode_id and e.owner_id=auth.uid())) with check (exists(select 1 from public.episodes e where e.id=episode_id and e.owner_id=auth.uid()));
